version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: WalletAPI
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_user_2025!$#&
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "wallet_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
